//! `brama version-gate …`: the version check `.github/workflows/version-check.yml`
//! runs on every change, carried by the candidate binary itself. A change is
//! refused when its declared version disagrees with what it did to Brama's
//! public surface, the commands `brama` advertises.
//!
//! The baseline is the committed `released-surface.json`, never regenerated by
//! the check: a check that rebuilt both sides would always agree with itself.

mod baseline;
mod contract;
mod rule;
mod surface;

use std::path::{Path, PathBuf};

use clap::Subcommand;

#[derive(Subcommand)]
pub(crate) enum VersionGateCommand {
    /// Print `{"surface": [...]}`: the commands this binary advertises, after
    /// checking that the scan of ROOT's src/main.rs agrees; with --revision,
    /// the scanned surface of that revision instead
    Surface {
        #[arg(long, default_value = ".")]
        root: PathBuf,
        #[arg(long)]
        revision: Option<String>,
    },
    /// Refuse when Cargo.toml's version disagrees with the version the rule
    /// requires for this binary's surface against released-surface.json
    Contract {
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// A candidate surface document instead of this binary's own
        #[arg(long)]
        candidate: Option<PathBuf>,
        /// First prove the rule and the comparison can both refuse
        #[arg(long)]
        self_check: bool,
    },
    /// Check released-surface.json against the channel that published it;
    /// with --write, regenerate it from the best channel instead
    Baseline {
        #[arg(long, default_value = ".")]
        root: PathBuf,
        #[arg(long)]
        write: bool,
    },
    /// Reproduce every case of AutoVersion's FIXTURES.md with this port
    Conformance {
        #[arg(long)]
        fixtures: PathBuf,
    },
}

fn own_surface(root: &Path, cli: &clap::Command) -> Result<Vec<String>, String> {
    let advertised = surface::advertised(cli);
    let scanned = surface::of_tree(root)?;
    if advertised != scanned {
        return Err(format!(
            "this binary advertises {advertised:?}, but the scan of src/main.rs finds {scanned:?}"
        ));
    }
    Ok(advertised)
}

fn document(surface: &[String]) -> String {
    serde_json::to_string_pretty(&serde_json::json!({ "surface": surface }))
        .expect("a list of names serialises")
}

fn dispatch(command: VersionGateCommand, cli: &clap::Command) -> Result<(), String> {
    match command {
        VersionGateCommand::Surface { root, revision } => {
            let names = match revision {
                Some(reference) => surface::of_revision(&root, &reference)?.0,
                None => own_surface(&root, cli)?,
            };
            println!("{}", document(&names));
            Ok(())
        }
        VersionGateCommand::Contract {
            root,
            candidate,
            self_check,
        } => {
            let names = match candidate {
                Some(path) => contract::read_json(&path)?["surface"]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .filter_map(serde_json::Value::as_str)
                    .map(str::to_string)
                    .collect(),
                None => own_surface(&root, cli)?,
            };
            contract::run(&root, &names, self_check)
        }
        VersionGateCommand::Baseline { root, write } if write => {
            let generated = baseline::best(&root)?;
            let text = format!(
                "{}\n",
                serde_json::to_string_pretty(&generated).expect("a JSON value serialises")
            );
            let path = root.join(contract::BASELINE);
            std::fs::write(&path, text).map_err(|error| format!("{}: {error}", path.display()))?;
            eprintln!("wrote {}", path.display());
            Ok(())
        }
        VersionGateCommand::Baseline { root, .. } => {
            println!("{}", baseline::check(&root)?);
            Ok(())
        }
        VersionGateCommand::Conformance { fixtures } => {
            let text = std::fs::read_to_string(&fixtures)
                .map_err(|error| format!("{}: {error}", fixtures.display()))?;
            if rule::conformance(&text)? {
                Ok(())
            } else {
                Err("this port does not reproduce AutoVersion's fixtures".into())
            }
        }
    }
}

pub(crate) fn run(command: VersionGateCommand, cli: clap::Command) {
    if let Err(detail) = dispatch(command, &cli) {
        eprintln!("::error::{detail}");
        std::process::exit(1);
    }
}
