//! The provider declarations this build ships with.

use super::{AuthKind, ProviderDescriptor, WireProtocol};

pub(super) const PROVIDERS: &[ProviderDescriptor] = &[
    ProviderDescriptor {
        id: "anthropic",
        display_name: "Anthropic",
        base_url: "https://api.anthropic.com",
        models_path: "/v1/models",
        chat_path: "/v1/messages",
        wire: WireProtocol::AnthropicMessages,
        auth: AuthKind::XApiKey,
        static_models: &["claude-haiku-4-5", "claude-opus-4-6", "claude-sonnet-4-6"],
    },
    ProviderDescriptor {
        id: "claude-code",
        display_name: "Claude Code (subscription)",
        base_url: "https://api.anthropic.com",
        models_path: "/v1/models",
        chat_path: "/v1/messages",
        wire: WireProtocol::AnthropicMessages,
        auth: AuthKind::AnthropicBearer,
        static_models: &["claude-haiku-4-5", "claude-opus-4-6", "claude-sonnet-4-6"],
    },
    ProviderDescriptor {
        id: "kimi",
        display_name: "Kimi (subscription)",
        base_url: "https://api.kimi.com/coding",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &["kimi-for-coding"],
    },
    ProviderDescriptor {
        id: "openai",
        display_name: "OpenAI",
        base_url: "https://api.openai.com",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "codex",
        display_name: "Codex (ChatGPT subscription)",
        base_url: "https://chatgpt.com/backend-api/codex",
        models_path: "/models",
        chat_path: "/responses",
        wire: WireProtocol::OpenAiResponses,
        auth: AuthKind::Bearer,
        static_models: &[
            "gpt-5.6-sol",
            "gpt-5.6-luna",
            "gpt-5.6-terra",
            "gpt-5.5",
            "gpt-5.3-codex-spark",
        ],
    },
    ProviderDescriptor {
        id: "openrouter",
        display_name: "OpenRouter",
        base_url: "https://openrouter.ai/api",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "groq",
        display_name: "Groq",
        base_url: "https://api.groq.com/openai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "mistral",
        display_name: "Mistral",
        base_url: "https://api.mistral.ai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "xai",
        display_name: "xAI",
        base_url: "https://api.x.ai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "deepseek",
        display_name: "DeepSeek",
        base_url: "https://api.deepseek.com",
        models_path: "/models",
        chat_path: "/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &["deepseek-chat", "deepseek-reasoner"],
    },
    ProviderDescriptor {
        id: "cerebras",
        display_name: "Cerebras",
        base_url: "https://api.cerebras.ai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "fireworks",
        display_name: "Fireworks",
        base_url: "https://api.fireworks.ai/inference",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "together",
        display_name: "Together",
        base_url: "https://api.together.xyz",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "nvidia",
        display_name: "NVIDIA NIM",
        base_url: "https://integrate.api.nvidia.com",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "moonshot",
        display_name: "Moonshot",
        base_url: "https://api.moonshot.ai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "zai",
        display_name: "Z.AI",
        base_url: "https://api.z.ai/api/paas",
        models_path: "/v4/models",
        chat_path: "/v4/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "qwen",
        display_name: "Qwen",
        base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "huggingface",
        display_name: "Hugging Face Inference",
        base_url: "https://router.huggingface.co",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "featherless",
        display_name: "Featherless",
        base_url: "https://api.featherless.ai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &["TheDrummer/Cydonia-24B-v4.3"],
    },
    ProviderDescriptor {
        id: "venice",
        display_name: "Venice",
        base_url: "https://api.venice.ai/api",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "novita",
        display_name: "Novita",
        base_url: "https://api.novita.ai/openai",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    ProviderDescriptor {
        id: "synthetic",
        display_name: "Synthetic",
        base_url: "https://api.synthetic.new",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
    // The local model server is authenticated. `AuthKind::None` was true when
    // this meant an unguarded loopback process; Stado now deploys vLLM with
    // `--api-key` and publishes the endpoint on the tailnet, and it mints the
    // bearer for exactly this caller (`provider:local-openai#token`, the item
    // the operator's capability route already names). With `None` the broker
    // returned an empty secret without reading anything and no Authorization
    // header was sent, so on 2026-09-05 every product chat took HTTP 401 from
    // the model host while the same request carrying that token answered in
    // 0.3 s — and nothing in the gateway logged a credential step at all,
    // because none happened.
    ProviderDescriptor {
        id: "local-openai",
        display_name: "Local OpenAI",
        base_url: "http://127.0.0.1",
        models_path: "/v1/models",
        chat_path: "/v1/chat/completions",
        wire: WireProtocol::OpenAiChat,
        auth: AuthKind::Bearer,
        static_models: &[],
    },
];
