"""Print brama's public surface: the commands its binary advertises.

What a caller of this product depends on is not its Rust symbols -- the library crate is
internal and nothing in the Stado release exposes it -- but **which commands the shipped
`brama` binary offers**. The release published by `.github/workflows/deploy-stado.yml`
is a runtime bundle whose entry points are `bin/brama` and the launcher that execs it,
so the command list is exactly the part of this repository other machines invoke by
name. Adding a command is a capability; removing or renaming one breaks whoever scripted
it yesterday. That makes the command list the public contract, and this prints it for
the shared versioning rule to compare.

Why the commands and not the HTTP routes: `brama` is a CLI first. `brama serve` starts
the OpenAI-compatible server, so the routes are reachable only *through* a command that
is itself part of this surface. The routes are a second, narrower contract owned by the
`serve` command; if `serve` disappeared the routes would go with it, so the command list
is the outer boundary and the right thing to version. The router declarations in
src/core/server.rs are deliberately not counted here.

Read from the clap declaration in src/main.rs by scanning it, never by building the
crate. A release decision must not depend on a machine having a Rust toolchain, this
crate's C-linked dependencies, or a warm cargo cache, and the gate has to run on a plain
checkout in seconds. The scan is deliberately narrow: it reads the enum named by the
`#[command(subcommand)]` field of the `#[derive(Parser)]` struct, which is the single
place clap builds the advertised list from. `--verify` re-reads the same list out of a
built binary's `--help` and refuses any disagreement, so the cheap path stays honest.

A command that dispatches but is not listed is private and is not counted: variants
carrying `hide` or `command(skip)` are dropped, exactly as `--help` drops them. Clap's
built-in `help` meta-command is dropped too -- every clap binary in the fleet prints it,
it is generated by the framework rather than declared here, and counting it would make a
dependency bump look like a change to this product's contract.

Usage:
    python3 scripts/surface.py [root]            # root defaults to the repository
    python3 scripts/surface.py --verify PATH     # also assert PATH --help agrees
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ZERO = int(False)
ONE = int(True)

PARSER_DERIVE = re.compile(r"#\[derive\([^)]*\bParser\b[^)]*\)\]")
SUBCOMMAND_FIELD = re.compile(
    r"#\[\s*(?:command|clap)\s*\(\s*subcommand\s*\)\s*\]\s*(?://[^\n]*\n\s*)*"
    r"(?:pub\s+)?\w+\s*:\s*(?:Option\s*<\s*)?(\w+)"
)
VARIANT = re.compile(r"^([A-Z][A-Za-z0-9_]*)\s*(?:[{(,=]|$)")
ATTRIBUTE = re.compile(r"^#\[")
NAME_OVERRIDE = re.compile(r"\bname\s*=\s*\"([^\"]+)\"")
RENAME_ALL = re.compile(r"\brename_all\s*=\s*\"([^\"]+)\"")
HIDDEN = re.compile(r"\bhide\s*=\s*true\b|\bskip\b")
HELP_COMMAND = re.compile(r"^\s\s+([a-z][a-z0-9-]*)(?:\s\s|$)")

MAIN = pathlib.Path("src") / "main.rs"
FRAMEWORK_COMMANDS = frozenset({"help"})


def enum_opener(source: str, name: str) -> re.Match:
    """Where `enum <name> {` begins."""
    opener = re.search(r"\benum\s+" + re.escape(name) + r"\s*\{", source)
    if opener is None:
        raise LookupError(f"no `enum {name}` in {MAIN}")
    return opener


def enum_attributes(source: str, name: str) -> str:
    """The attribute lines attached directly above `enum <name>`.

    Only these can retarget how clap renders the variant names, so they are the one
    place worth reading before trusting the default kebab-case rendering.
    """
    above = source[: enum_opener(source, name).start()].splitlines()
    attached = []
    while above:
        line = above.pop().strip()
        if ATTRIBUTE.match(line):
            attached.append(line)
        elif line and not line.startswith("//"):
            break
    return " ".join(attached)


def enum_body(source: str, name: str) -> str:
    """The text between the braces of `enum <name> { ... }`."""
    opener = enum_opener(source, name)
    start = opener.end()
    depth = ONE
    for index in range(start, len(source)):
        character = source[index]
        if character == "{":
            depth += ONE
        elif character == "}":
            depth -= ONE
            if depth == ZERO:
                return source[start:index]
    raise LookupError(f"`enum {name}` is never closed in {MAIN}")


def subcommand_enum(source: str) -> str:
    """The enum clap builds the advertised command list from."""
    parser = PARSER_DERIVE.search(source)
    if parser is None:
        raise LookupError(f"no #[derive(Parser)] entry point in {MAIN}")
    field = SUBCOMMAND_FIELD.search(source, parser.end())
    if field is None:
        raise LookupError(f"the Parser struct in {MAIN} declares no subcommand field")
    return field.group(ONE)


def kebab(variant: str) -> str:
    """A variant name as clap's default `kebab-case` renderer prints it.

    Splits where a lowercase or digit meets an uppercase letter, and where a run of
    uppercase letters is followed by a lowercase one, so `CollectTaskQuality` becomes
    `collect-task-quality`, `Mcp` stays `mcp`, and `HTTPServe` becomes `http-serve`.
    """
    split = re.sub(r"([a-z0-9])([A-Z])", r"\g<1>-\g<2>", variant)
    split = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\g<1>-\g<2>", split)
    return split.replace("_", "-").lower()


def declared_commands(root: pathlib.Path) -> list:
    """Every command the clap declaration in src/main.rs advertises."""
    source = (root / MAIN).read_text(encoding="utf-8")
    enum_name = subcommand_enum(source)
    body = enum_body(source, enum_name)

    rename = RENAME_ALL.search(enum_attributes(source, enum_name))
    if rename is not None and rename.group(ONE) != "kebab-case":
        raise LookupError(
            f"enum {enum_name} overrides rename_all to {rename.group(ONE)!r}; "
            "this scan only renders clap's default kebab-case"
        )

    names = set()
    attributes = []
    depth = ZERO
    for raw in body.splitlines():
        line = raw.strip()
        if depth == ZERO and line and not line.startswith("//"):
            if ATTRIBUTE.match(line):
                attributes.append(line)
            else:
                variant = VARIANT.match(line)
                if variant is not None:
                    joined = " ".join(attributes)
                    if not HIDDEN.search(joined):
                        override = NAME_OVERRIDE.search(joined)
                        names.add(
                            override.group(ONE) if override else kebab(variant.group(ONE))
                        )
                    attributes = []
        depth += line.count("{") + line.count("(") + line.count("[")
        depth -= line.count("}") + line.count(")") + line.count("]")
    return sorted(names - FRAMEWORK_COMMANDS)


def advertised_by(binary: str) -> list:
    """Every command `<binary> --help` prints, straight from a built artifact."""
    printed = subprocess.run(
        [binary, "--help"], check=True, capture_output=True, text=True
    ).stdout
    if "Commands:" not in printed:
        raise LookupError(f"{binary} --help prints no command list")
    names = set()
    for line in printed.split("Commands:", ONE)[ONE].splitlines():
        if not line.strip():
            if names:
                break
            continue
        found = HELP_COMMAND.match(line)
        if found is not None:
            names.add(found.group(ONE))
    return sorted(names - FRAMEWORK_COMMANDS)


def main(argv: list) -> int:
    arguments = list(argv)
    binary = None
    if "--verify" in arguments:
        marker = arguments.index("--verify")
        del arguments[marker]
        if len(arguments) == marker:
            print("--verify needs a path to a built brama binary", file=sys.stderr)
            return ONE
        binary = arguments.pop(marker)

    root = (
        pathlib.Path(arguments[ZERO])
        if arguments
        else pathlib.Path(__file__).resolve().parent.parent
    )
    surface = declared_commands(root)
    if not surface:
        print(f"no commands found in {root / MAIN}", file=sys.stderr)
        return ONE

    if binary is not None:
        built = advertised_by(binary)
        if built != surface:
            print(
                f"{binary} advertises {built}, but {MAIN} declares {surface}",
                file=sys.stderr,
            )
            return ONE
        print(f"{binary} --help agrees with {MAIN}", file=sys.stderr)

    print(json.dumps({"surface": surface}, indent=ONE + ONE))
    return ZERO


if __name__ == "__main__":
    sys.exit(main(sys.argv[ONE:]))
